-- PlanetsOS Risk Training Schema
-- Run this after the initial supabase_migration.sql migration.

-- ==================== PREDICTION EVENTS ====================
CREATE TABLE IF NOT EXISTS incident_prediction_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id TEXT NOT NULL,
    predicted_issue_type TEXT NOT NULL,
    predicted_category TEXT NOT NULL,
    predicted_risk_level TEXT NOT NULL CHECK (predicted_risk_level IN ('low', 'medium', 'high', 'critical')),
    predicted_responder_type TEXT NOT NULL,
    confidence NUMERIC(5, 4) NOT NULL DEFAULT 0,
    requires_human_review BOOLEAN DEFAULT FALSE,
    model_version TEXT NOT NULL,
    feature_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    prediction_sources JSONB NOT NULL DEFAULT '[]'::jsonb,
    learning_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    reason_codes JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE incident_prediction_events ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'incident_prediction_events'
          AND policyname = 'Anyone can insert prediction events'
    ) THEN
        CREATE POLICY "Anyone can insert prediction events"
            ON incident_prediction_events FOR INSERT
            WITH CHECK (TRUE);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'incident_prediction_events'
          AND policyname = 'Anyone can view prediction events'
    ) THEN
        CREATE POLICY "Anyone can view prediction events"
            ON incident_prediction_events FOR SELECT
            USING (TRUE);
    END IF;
END $$;

-- ==================== VERIFIED FEEDBACK ====================
CREATE TABLE IF NOT EXISTS incident_training_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id TEXT NOT NULL,
    issue_type TEXT NOT NULL,
    predicted_category TEXT,
    predicted_risk_level TEXT CHECK (predicted_risk_level IN ('low', 'medium', 'high', 'critical')),
    predicted_responder_type TEXT,
    final_category TEXT NOT NULL,
    final_risk_level TEXT NOT NULL CHECK (final_risk_level IN ('low', 'medium', 'high', 'critical')),
    final_responder_type TEXT NOT NULL,
    final_status TEXT DEFAULT 'resolved',
    emergency_escalated BOOLEAN DEFAULT FALSE,
    was_prediction_correct BOOLEAN,
    reviewer_department_id UUID REFERENCES departments(id) ON DELETE SET NULL,
    responder_notes TEXT,
    feature_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    model_version TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE incident_training_feedback ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'incident_training_feedback'
          AND policyname = 'Anyone can insert training feedback'
    ) THEN
        CREATE POLICY "Anyone can insert training feedback"
            ON incident_training_feedback FOR INSERT
            WITH CHECK (TRUE);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'incident_training_feedback'
          AND policyname = 'Anyone can view training feedback'
    ) THEN
        CREATE POLICY "Anyone can view training feedback"
            ON incident_training_feedback FOR SELECT
            USING (TRUE);
    END IF;
END $$;

-- ==================== INDEXES ====================
CREATE INDEX IF NOT EXISTS idx_prediction_events_ticket_id
    ON incident_prediction_events(ticket_id);

CREATE INDEX IF NOT EXISTS idx_prediction_events_risk_level
    ON incident_prediction_events(predicted_risk_level);

CREATE INDEX IF NOT EXISTS idx_training_feedback_ticket_id
    ON incident_training_feedback(ticket_id);

CREATE INDEX IF NOT EXISTS idx_training_feedback_issue_type
    ON incident_training_feedback(issue_type);

CREATE INDEX IF NOT EXISTS idx_training_feedback_final_risk
    ON incident_training_feedback(final_risk_level);
